[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.start]
cmds = [
  'python manage.py migrate',
  'gunicorn backend.wsgi:application --bind 0.0.0.0:8000'
]

